export { default as AboutSection } from './AboutSection'
export { default as CertificationsSection } from './CertificationsSection'
export { default as EducationSection } from './EducationSection'
export { default as ExperienceSection } from './ExperienceSection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as TechStackSection } from './TechStackSection'
